AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Petstore API - petstore::petstore
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  PetstoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: petstore.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/petstore-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PetstoreApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: PetstoreApi
